analog_processor:
  ros__parameters:
    sensors:
      co:
        pin: 4
        enabled: true
        unit: "V"
        conversion: "voltage"
      no2:
        pin: 2
        enabled: true
        unit: "V"
        conversion: "voltage"
      nh3:
        pin: 3
        enabled: true
        unit: "V"
        conversion: "voltage"
      rh:
        pin: 1
        enabled: true
        unit: "%"
        conversion: "humidity"
      temp:
        pin: 0
        enabled: true
        unit: "Â°C"
        conversion: "temperature"
    publish_diagnostic_array: true
    publish_float_array: true
    publish_mean_analog: true
    voltage_offset: 0.0
    update_rate: 1.0    # Update frequency in Hz (1.0 = once per second)

streaming:
  ros__parameters:
    processed_analog:
      port: 5003
